name: Deploy Server to Droplet

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect & deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_KEY }}

          script: |
            set -e

            cd /var/www/infotech/infoTechIndiaServer

            git fetch --all
            git reset --hard origin/master

            npm install

            pm2 restart infotech-backend || pm2 start npm --name infotech-backend -- start

            pm2 save